import sys

from scene import *
from api import *
from config import *


scene=SimplePickPlaceScene()
get_names_on_table=scene.get_names_on_table
get_location_by_name=scene.get_pose_by_name
get_box_position=scene.get_pad_postion
move_tool=scene.grasp_tool.move_for_grasp
grasp=scene.grasp_tool.grasp
ungrasp=scene.grasp_tool.ungrasp


def plan():
    print("This function plan() has not been generated by LLM.")
    print(f"Please run {TINYROBOTBENCH_root_path}+request_llm_server.py to get the plan() definition from the LLM ")


def main():
    if len(sys.argv)>1:
        plan_str = sys.argv[1]
        exec(plan_str, globals())
    plan()


if __name__=="__main__":
    main()